# l9-ci-core repository implementation.
#
# The root Makefile is generated by the Core-owned V2 compiler. This file owns
# only l9-ci-core implementation of the portable setup/validate/check/test ABI.
# It must not implement organization governance or publication.
PYTHON ?= python3
L9_REPO := $(PYTHON) -m tools.l9_repo --workspace "$(CURDIR)"

.PHONY: \
	repo-setup \
	repo-validate \
	repo-check \
	repo-test \
	repo-clean \
	repo-doctor \
	change-policy \
	agent-check \
	status \
	reconcile \
	verify-generated \
	attest-control-plane \
	check-release-writers

# ---------------------------------------------------------------------------
# Portable ABI implementation: Core self-hosts through these Repo.mk leaves.
# ---------------------------------------------------------------------------
repo-setup:
	@$(PYTHON) -m pip install -r requirements-ci.txt
	@$(PYTHON) -m pip install -r requirements-repo-runtime.txt

repo-validate:
	@$(L9_REPO) validate
	@$(L9_REPO) core-validate
	@$(PYTHON) tools/check_workflow_integrity.py

repo-check:
	@$(PYTHON) tools/check_toolchain_versions.py
	@$(PYTHON) -m ruff check .
	@$(PYTHON) -m ruff format --check .
	@$(PYTHON) -m mypy

repo-test:
	@$(PYTHON) -m unittest discover --start-directory tests --pattern 'test_*.py' --verbose

repo-clean:
	@$(L9_REPO) clean

repo-doctor:
	@$(L9_REPO) doctor

# ---------------------------------------------------------------------------
# Core-local operations, intentionally outside the portable consumer ABI.
# ---------------------------------------------------------------------------
change-policy: ## Show Core change-policy obligations
	@$(L9_REPO) change-policy

agent-check: ## Run Core evidence-bearing completion checks
	@$(L9_REPO) agent-check

status: ## Show Core-local repository state
	@$(L9_REPO) status

reconcile: ## Regenerate the root Makefile from the Core canonical template
	@$(L9_REPO) reconcile

verify-generated: ## Verify generated repository artifacts without mutation
	@$(L9_REPO) verify-generated

attest-control-plane: ## Attest the live GitHub control plane
	@$(PYTHON) tools/verify_control_plane.py

check-release-writers: ## Validate release-writer namespace uniqueness
	@$(PYTHON) tools/check_release_writers.py
