# GENERATED by Quantum-L9/l9-ci-core tools.l9_make. DO NOT EDIT.
# capability-plan-sha256: 3e347d477591620d6fb803acca60af491f959099bcd75330ba4a52aaf7e3f6cc
# Repository-native targets belong in Repo.local.mk. Governance remains delegated by Makefile.
PYTHON ?= python3
L9_REPO := $(PYTHON) -m tools.l9_repo --workspace "$(CURDIR)"

.PHONY: \
	repo-check \
	repo-clean \
	repo-doctor \
	repo-setup \
	repo-test \
	repo-validate

repo-check:
	@$(L9_REPO) check

repo-clean:
	@$(L9_REPO) clean

repo-doctor:
	@$(L9_REPO) doctor

repo-setup:
	@$(L9_REPO) setup

repo-test:
	@$(L9_REPO) test

repo-validate:
	@$(L9_REPO) validate
