# GENERATED by Quantum-L9/l9-ci-core tools.l9_make. DO NOT EDIT.
#
# This public interface is intentionally universal and thin:
#   - Repo.mk is the generated, provenance-bound local capability adapter.
#   - Repo.local.mk is an optional repository-owned extension layer.
#   - Governance and publication are delegated only to the installed l9 dispatcher.
#
# Do not place product logic, Git publication logic, or GitHub API logic here.
# Recover generated artifacts with: python3 -m tools.l9_repo reconcile
.DEFAULT_GOAL := help
SHELL := /usr/bin/env bash
.SHELLFLAGS := -eu -o pipefail -c
L9 ?= l9

# The generated standard adapter is required. Local extensions are optional:
# an adopting repository may start with the universal capabilities only.
include Repo.mk
-include Repo.local.mk

L9_STANDARD_TARGETS := \
	help \
	capabilities \
	doctor \
	setup \
	build \
	lint \
	test \
	validate \
	check \
	package \
	generate \
	benchmark \
	status \
	clean \
	wiring-check \
	start \
	workspace-clean \
	pr

.PHONY: $(L9_STANDARD_TARGETS)

help: ## Show public repository commands
	@awk '\
		BEGIN { FS = ":.*## "; } \
		/^[A-Za-z0-9_.-]+:.*## / { \
			printf "  %-24s %s\\n", $$1, $$2; \
		}' $(MAKEFILE_LIST)

capabilities: ## Show all standard capability states and their provenance
	@$(MAKE) --no-print-directory repo-capabilities

# Standard local capabilities are generated in Repo.mk.
doctor: repo-doctor ## Verify local prerequisites and wiring
setup: repo-setup ## Establish local development dependencies
build: repo-build ## Produce the primary build artifact when required
lint: repo-lint ## Run static analysis, style, and type checks
check: repo-check ## Compatibility alias for the historical static-check target
test: repo-test ## Execute repository tests
validate: repo-validate ## Run the canonical repository readiness gate
package: repo-package ## Produce a distributable local artifact when required
generate: repo-generate ## Regenerate derived artifacts when supported
benchmark: repo-benchmark ## Execute repository benchmarks when supported
status: repo-status ## Report local repository state
clean: repo-clean ## Remove disposable repository-local outputs

# Cross-repository governance remains an external handoff. No local façade,
# generated adapter, or extension layer owns Git/GitHub publication semantics.
wiring-check: ## Verify Governance wiring for this repository
	@$(L9) wiring-check

start: ## Run the governed session-start pipeline
	@$(L9) start

workspace-clean: ## Run governed workspace reconciliation
	@$(L9) workspace-clean

pr: ## Gate and publish through Cursor-Governance
	@$(L9) pr
