#!/usr/bin/env python3
"""Regenerate a hash-locked Semgrep install contract for ``install-semgrep``.

The lock names every package version pip resolves for ``semgrep==<version>``
and every PyPI wheel digest of each exact version, so a runner can only
install those versions from those bytes (``--require-hashes``,
``--only-binary :all:``). Operator tool, run deliberately when Core selects a
new central Semgrep version; never executed by a workflow.

    python3 .github/actions/install-semgrep/lock_semgrep.py --version 1.171.0

Resolution happens through pip itself (``pip download`` for CPython
``--python`` on manylinux x86_64, the runner class ``org-ci.yml`` names), so
the version set is the one pip would choose there. Digests come from the PyPI
JSON API, and the locally downloaded wheel must be among them; every wheel of
the release is listed so the lock stays correct across compatible platform
tags while still refusing any unlisted version or bytes. Source distributions
are never listed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import ssl
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

PYPI = "https://pypi.org/pypi"
PLATFORMS = (
    "manylinux_2_34_x86_64",
    "manylinux_2_28_x86_64",
    "manylinux_2_17_x86_64",
    "manylinux2014_x86_64",
)
DEFAULT_PIP = "26.2.1"
VERSION = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")


class LockError(RuntimeError):
    """The lock could not be produced honestly."""


def canonical(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def resolve_closure(version: str, python: str, destination: Path) -> list[Path]:
    """Ask pip for the wheel closure of ``semgrep==version`` on the runner class."""
    abi = "cp" + python.replace(".", "")
    argv = [
        sys.executable,
        "-m",
        "pip",
        "download",
        f"semgrep=={version}",
        "--dest",
        str(destination),
        "--only-binary",
        ":all:",
        "--python-version",
        python,
        "--implementation",
        "cp",
        "--abi",
        abi,
        "--quiet",
    ]
    for platform in PLATFORMS:
        argv.extend(["--platform", platform])
    completed = subprocess.run(argv, check=False, capture_output=True, text=True)
    if completed.returncode != 0:
        raise LockError(f"pip download failed:\n{completed.stderr.strip()}")
    wheels = sorted(destination.glob("*.whl"))
    if not wheels:
        raise LockError("pip download produced no wheels")
    return wheels


def wheel_digests(
    name: str, version: str, context: ssl.SSLContext
) -> tuple[str, list[str]]:
    """Return the canonical project name and every wheel sha256 of the release."""
    url = f"{PYPI}/{name}/{version}/json"
    request = urllib.request.Request(url, headers={"Accept": "application/json"})
    # nosemgrep: python.lang.security.audit.dynamic-urllib-use-detected.dynamic-urllib-use-detected -- https PyPI prefix fixed above
    with urllib.request.urlopen(request, context=context, timeout=60) as response:  # noqa: S310
        document = json.load(response)
    files = document.get("urls") or []
    digests = sorted(
        {
            str(entry["digests"]["sha256"])
            for entry in files
            if entry.get("packagetype") == "bdist_wheel" and not entry.get("yanked")
        }
    )
    if not digests:
        raise LockError(f"{name}=={version}: PyPI lists no wheel for this release")
    return canonical(str(document["info"]["name"])), digests


def render(version: str, python: str, entries: list[tuple[str, str, list[str]]]) -> str:
    """Render lock text; ``entries`` are ``(project, version, digests)``."""
    lines = [
        "# Hash-locked install contract for the central Semgrep provider.",
        f"# Generated by lock_semgrep.py from a pip resolution of semgrep=={version}",
        f"# for CPython {python} on manylinux x86_64; every wheel digest of each",
        "# exact version is listed so pip can only install these versions from",
        "# these bytes (--require-hashes, --only-binary :all:). Regenerate with",
        "# that script when Core selects a new version; never hand-edit a digest.",
        "",
    ]
    for project, pinned, digests in entries:
        lines.append(f"{project}=={pinned} \\")
        for index, digest in enumerate(digests):
            tail = " \\" if index < len(digests) - 1 else ""
            lines.append(f"    --hash=sha256:{digest}{tail}")
    return "\n".join(lines) + "\n"


def build(version: str, python: str, pip_version: str, context: ssl.SSLContext) -> str:
    with tempfile.TemporaryDirectory() as scratch:
        wheels = resolve_closure(version, python, Path(scratch))
        entries: list[tuple[str, str, list[str]]] = []
        seen: set[str] = set()
        for wheel in wheels:
            name, pinned = wheel.name.split("-")[:2]
            project, digests = wheel_digests(name, pinned, context)
            if project in seen:
                raise LockError(f"{project}: resolved twice")
            local = hashlib.sha256(wheel.read_bytes()).hexdigest()
            if local not in digests:
                raise LockError(f"{project}=={pinned}: downloaded wheel is not on PyPI")
            seen.add(project)
            entries.append((project, pinned, digests))
    if "semgrep" not in seen:
        raise LockError("resolution did not include semgrep itself")
    if "pip" not in seen:
        project, digests = wheel_digests("pip", pip_version, context)
        entries.append((project, pip_version, digests))
    entries.sort(key=lambda entry: entry[0])
    return render(version, python, entries)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--version", required=True, help="exact Semgrep x.y.z")
    parser.add_argument("--python", default="3.12", help="CPython minor, e.g. 3.12")
    parser.add_argument("--pip", default=DEFAULT_PIP, help="pip version to lock")
    parser.add_argument(
        "--output",
        default=None,
        help="lock path (default: locks/semgrep-<version>.txt beside this script)",
    )
    parser.add_argument(
        "--ca-bundle",
        default=os.environ.get("SSL_CERT_FILE") or None,
        help="CA bundle for PyPI (default: SSL_CERT_FILE or the system store)",
    )
    arguments = parser.parse_args(argv)
    if not VERSION.match(arguments.version):
        print("lock_semgrep: --version must be an exact x.y.z", file=sys.stderr)
        return 2
    if not re.fullmatch(r"3\.[0-9]+", arguments.python):
        print("lock_semgrep: --python must be 3.N", file=sys.stderr)
        return 2
    output = (
        Path(arguments.output)
        if arguments.output
        else Path(__file__).resolve().parent
        / "locks"
        / f"semgrep-{arguments.version}.txt"
    )
    context = ssl.create_default_context(cafile=arguments.ca_bundle)
    try:
        text = build(arguments.version, arguments.python, arguments.pip, context)
    except (LockError, OSError, KeyError, ValueError) as error:
        print(f"lock_semgrep: {error}", file=sys.stderr)
        return 1
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(f"lock_semgrep: wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
