#!/usr/bin/env python3
"""Regenerate semgrep identity-map files from the live registry.

Each preset invokes a fixed set of Semgrep registry packs (see
``PRESET_SOURCES`` below). This script fetches the exact same packs
from ``https://semgrep.dev/c/<pack>``, enumerates every rule ID they
currently contain, and ensures each one has an explicit
``l9.identity-map/v1`` entry.

Design constraints (do not change without re-reading
``l9_ci.identity.resolver.resolve_rule_identity`` in l9-ci-sdk first):

- Never removes an existing mapping. A rule ID that disappears from a
  registry pack may still appear in already-recorded findings, waivers,
  or dashboards; deleting its mapping would make historical data
  unresolvable. Removed-upstream rule IDs are reported, not deleted.
- Never overwrites an existing ``canonical_rule_id``. If a rule has been
  curated to a non-default canonical ID (e.g. to reconcile it with a
  second provider later), that curation is manual state this script
  must not clobber. Only genuinely new rule IDs get the default
  ``l9:semgrep:<rule_id>`` mapping.
- Deterministic output: sorted keys, stable JSON formatting, so repeated
  runs against an unchanged registry produce a byte-identical file.

Exit codes:
  0 — up to date (or successfully regenerated in write mode)
  1 — check mode found drift (files would change)
  2 — usage or network/parse error
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any

import yaml

REGISTRY_BASE = "https://semgrep.dev/c/"
REPO_ROOT = Path(__file__).resolve().parent.parent

# Preset name -> registry packs that preset's l9-analysis.yml actually
# invokes (`semgrep scan --config ...`). Keep this in sync with the
# `semgrep scan` step in each preset's workflow.
PRESET_SOURCES: dict[str, tuple[str, ...]] = {
    "python": ("p/python",),
    "typescript": ("p/typescript", "p/javascript"),
}

CANONICAL_NAMESPACE = "l9:semgrep:"
IDENTITY_MAP_SCHEMA = "l9.identity-map/v1"


class RegenerationError(RuntimeError):
    pass


def fetch_rule_ids(pack: str, *, timeout: float = 30.0) -> set[str]:
    url = f"{REGISTRY_BASE}{pack}"
    try:
        with urllib.request.urlopen(url, timeout=timeout) as response:  # noqa: S310
            payload = response.read()
    except OSError as error:
        msg = f"failed to fetch {url}: {error}"
        raise RegenerationError(msg) from error
    try:
        document = yaml.safe_load(payload)
    except yaml.YAMLError as error:
        msg = f"failed to parse registry config {url}: {error}"
        raise RegenerationError(msg) from error
    if not isinstance(document, dict) or "rules" not in document:
        msg = f"registry config {url} has no top-level 'rules' key"
        raise RegenerationError(msg)
    rule_ids: set[str] = set()
    for rule in document["rules"]:
        rule_id = rule.get("id") if isinstance(rule, dict) else None
        if not isinstance(rule_id, str) or not rule_id:
            msg = f"registry config {url} has a rule with no valid 'id'"
            raise RegenerationError(msg)
        rule_ids.add(rule_id)
    return rule_ids


def load_existing(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {
            "schema": IDENTITY_MAP_SCHEMA,
            "metadata": {"provider_id": "semgrep", "version": "1"},
            "rules": {},
        }
    return json.loads(path.read_text(encoding="utf-8"))


def build_updated_document(
    existing: dict[str, Any],
    live_rule_ids: set[str],
) -> tuple[dict[str, Any], list[str], list[str]]:
    existing_rules: dict[str, Any] = dict(existing.get("rules", {}))
    added = sorted(rule_id for rule_id in live_rule_ids if rule_id not in existing_rules)
    removed_upstream = sorted(
        rule_id for rule_id in existing_rules if rule_id not in live_rule_ids
    )
    for rule_id in added:
        existing_rules[rule_id] = {
            "canonical_rule_id": f"{CANONICAL_NAMESPACE}{rule_id}",
        }
    metadata = dict(existing.get("metadata", {"provider_id": "semgrep", "version": "1"}))
    if added:
        try:
            metadata["version"] = str(int(metadata.get("version", "1")) + 1)
        except ValueError:
            metadata["version"] = "1"
    document = {
        "schema": IDENTITY_MAP_SCHEMA,
        "metadata": metadata,
        "rules": {rule_id: existing_rules[rule_id] for rule_id in sorted(existing_rules)},
        "note": existing.get(
            "note",
            (
                "Generated by tools/regenerate_identity_maps.py from the exact "
                "registry configs each preset invokes. New upstream rules are "
                "added automatically with a default l9:semgrep:<rule_id> "
                "mapping; curated overrides are preserved on regeneration."
            ),
        ),
    }
    return document, added, removed_upstream


def render(document: dict[str, Any]) -> str:
    return json.dumps(document, indent=2, sort_keys=False) + "\n"


def process_preset(preset: str, packs: tuple[str, ...], *, check_only: bool) -> bool:
    """Return True if the identity-map file would change (or did change)."""
    live_rule_ids: set[str] = set()
    for pack in packs:
        live_rule_ids |= fetch_rule_ids(pack)

    path = (
        REPO_ROOT
        / "presets"
        / preset
        / ".github"
        / "governance"
        / "semgrep-identity-map.yaml"
    )
    existing = load_existing(path)
    updated, added, removed_upstream = build_updated_document(existing, live_rule_ids)
    rendered = render(updated)
    changed = not path.is_file() or path.read_text(encoding="utf-8") != rendered

    label = f"[{preset}]"
    if added:
        print(f"{label} {len(added)} new rule(s): {', '.join(added)}")
    if removed_upstream:
        print(
            f"{label} {len(removed_upstream)} rule(s) no longer in the registry "
            f"pack (kept for historical resolution): {', '.join(removed_upstream)}"
        )
    if not added and not removed_upstream:
        print(f"{label} up to date ({len(live_rule_ids)} rules)")

    if changed and not check_only:
        path.write_text(rendered, encoding="utf-8")
        print(f"{label} wrote {path.relative_to(REPO_ROOT)}")

    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift without writing files; exit 1 if any preset is stale",
    )
    args = parser.parse_args(argv)

    any_changed = False
    try:
        for preset, packs in PRESET_SOURCES.items():
            changed = process_preset(preset, packs, check_only=args.check)
            any_changed = any_changed or changed
    except RegenerationError as error:
        print(f"regenerate_identity_maps: {error}", file=sys.stderr)
        return 2

    if args.check and any_changed:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
