name: L9 Self Analysis

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    uses: ./.github/workflows/analyze-semgrep.yml
    permissions:
      actions: read
      checks: write
      contents: read
    with:
      profile: pr_fast
      matrix-id: core-semgrep
      sdk-revision: "{{SDK_CODE_SHA}}"
      semgrep-configs-json: '["p/python"]'
